/**
 * Données des restaurants de Montpellier
 * Inclut les coordonnées GPS pour la carte interactive
 */

const restaurantsData = [
  {
    id: 1,
    name: "ARTISANE",
    address: "19 Rue du Palais des Guilhem, 34000 Montpellier",
    phone: "04 99 06 50 80",
    closedDays: "mercredi et jeudi",
    rating: 5.0,
    lat: 43.61140019999999,
    lng: 3.875159599999999,
    type: "gastronomique",
    price: "€€€",
    quartier: "centre-historique",
    specialities: ["créative", "gastronomique", "cuisine d'auteur"],
    comment: "La chef est incroyablement douée, avec une intelligence culinaire et une grâce qui nous ont vraiment impressionnés. Elle a le don de trouver un équilibre créatif dans des compositions très élégantes.",
    reviewer: "Sophie M.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/1.jpg"
  },
  {
    id: 2,
    name: "Ébullition",
    address: "10 Rue du Pila St Gély, 34000 Montpellier",
    phone: "09 86 10 84 84",
    closedDays: "lundi, samedi et dimanche",
    rating: 4.9,
    lat: 43.6133242,
    lng: 3.8798597,
    type: "gastronomique",
    price: "€€€",
    quartier: "centre-historique",
    specialities: ["française", "gastronomique", "cuisine créative"],
    comment: "Ce fut le point culminant de notre visite à Montpellier. Nous avons pris le menu dégustation en 7 plats et avons savouré chaque assiette - présentation magnifique, textures variées et profondeur de saveurs dans chaque sauce.",
    reviewer: "Pierre L.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/2.jpg"
  },
  {
    id: 3,
    name: "Les t'OCqués",
    address: "15 Rue Roucher, 34000 Montpellier",
    phone: "04 67 63 42 86",
    closedDays: "lundi et dimanche",
    rating: 4.9,
    lat: 43.6082964,
    lng: 3.874452,
    type: "bistronomique",
    price: "€€",
    quartier: "centre-historique",
    specialities: ["poisson", "fruits de mer", "cuisine méditerranéenne"],
    comment: "Les t'OCqués est un véritable joyau culinaire. La cuisine y est excellente et passionnante, particulièrement les plats de poisson qui sont à la fois savoureux et magnifiquement présentés.",
    reviewer: "Christophe N.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/3.jpg"
  },
  {
    id: 4,
    name: "Le Bistrok Montpellier",
    address: "47 Rue de l'Aiguillerie, 34000 Montpellier",
    phone: "07 68 87 74 93",
    closedDays: "dimanche",
    rating: 4.8,
    lat: 43.61210150000001,
    lng: 3.8791063,
    type: "bistro",
    price: "€€",
    quartier: "écusson",
    specialities: ["française", "méditerranéenne", "burrata"],
    comment: "Nourriture superbe dans une très belle ambiance (jolies tables et chaises tendance sur une petite place sous un arbre, en plein cœur du centre historique de Montpellier).",
    reviewer: "Lucie M.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/4.jpg"
  },
  {
    id: 5,
    name: "Pastis Restaurant",
    address: "3 Rue Terral, 34000 Montpellier",
    phone: "04 67 66 37 26",
    closedDays: "lundi et dimanche",
    rating: 4.8,
    lat: 43.6099292,
    lng: 3.8738383,
    type: "gastronomique",
    price: "€€€",
    quartier: "centre-historique",
    specialities: ["française", "cuisine moderne", "gastronomique"],
    comment: "Le personnel incroyablement sympathique offre une expérience de haute cuisine française détendue avec leur propre touche moderne.",
    reviewer: "Richard D.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/5.jpg"
  },
  {
    id: 6,
    name: "Restaurant Leclère",
    address: "8 Rue André Michel, 34000 Montpellier",
    phone: "04 67 68 96 85",
    closedDays: "lundi et dimanche",
    rating: 4.8,
    lat: 43.6067829,
    lng: 3.873926699999999,
    type: "bistronomique",
    price: "€€",
    quartier: "quartier-des-beaux-arts",
    specialities: ["cuisine du marché", "produits frais", "française"],
    comment: "C'est probablement le meilleur rapport qualité-prix que j'ai jamais connu. L'ambiance est très décontractée mais élégante.",
    reviewer: "Marc P.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/6.jpg"
  },
  {
    id: 7,
    name: "Jardin Des Sens",
    address: "Place de la Canourgue, 34000 Montpellier",
    phone: "04 99 66 18 18",
    closedDays: "lundi et dimanche",
    rating: 4.8,
    lat: 43.6118344,
    lng: 3.874941899999999,
    type: "gastronomique",
    price: "€€€€",
    quartier: "centre-historique",
    specialities: ["haute cuisine", "gastronomique", "création culinaire"],
    comment: "Endroit incroyable, tout, de la cuisine à l'atmosphère et au service, est simplement parfait ! Tous les plats sont extrêmement délicieux.",
    reviewer: "Nicolas H.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/7.jpg"
  },
  {
    id: 8,
    name: "LE GURU",
    address: "36 Rue de l'Argenterie, 34000 Montpellier",
    phone: "04 99 62 24 50",
    closedDays: "lundi et mardi",
    rating: 4.8,
    lat: 43.6081549,
    lng: 3.8773556,
    type: "fusion",
    price: "€€",
    quartier: "centre-historique",
    specialities: ["fusion asiatique", "française", "créative"],
    comment: "À la hauteur de sa formidable réputation, ce merveilleux petit restaurant propose de délicieux plats de fusion asiatique-française.",
    reviewer: "David A.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/8.jpg"
  },
  {
    id: 9,
    name: "Le Bourdon",
    address: "35 Rue Saint-Guilhem, 34000 Montpellier",
    phone: "04 48 79 64 64",
    closedDays: "lundi",
    rating: 4.7,
    lat: 43.60893609999999,
    lng: 3.8739352,
    type: "bistro",
    price: "€€",
    quartier: "centre-historique",
    specialities: ["française", "traditionnelle", "produits du terroir"],
    comment: "Tout ce que j'ai commandé était vraiment délicieux. L'atmosphère est chaleureuse et confortable.",
    reviewer: "Kevin J.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/9.jpg"
  },
  {
    id: 10,
    name: "La Réserve Rimbaud",
    address: "820 Avenue de Saint-Maur, 34000 Montpellier",
    phone: "04 67 72 52 53",
    closedDays: "samedi et dimanche",
    rating: 4.6,
    lat: 43.616726,
    lng: 3.892808400000001,
    type: "gastronomique",
    price: "€€€",
    quartier: "les-aubes",
    specialities: ["cuisine raffinée", "poisson", "bord du Lez"],
    comment: "Tout était plus qu'excellent ! J'ai adoré l'ambiance, c'était très propre et apaisant.",
    reviewer: "Nathalie H.",
    image: "https://cdnjs.cloudflare.com/ajax/libs/galereya/0.9.0/images/10.jpg"
  }
];
